### ISSUE TITLE
[Suggestion] Add config to always enter Online, LAN or nothing so I'd choose

### ISSUE THREAD

**Issue by SirPrepu** [alexanderjoe/LCSymphony#1]
Simple as the title says, I love the ping feature but I sometimes play LAN games to test some mods.

**Comment by alexanderjoe** [comment]
@julioSantosAlbarregas Just want to double-check, you are not expecting to see the ping display in a LAN game correct? The way I had to implement it is a little janky in the way it just pings the nearest steam server to the host instead of directly pinging the host. I would be happy to implement it here over the weekend.

**Comment by alexanderjoe** [comment]
https://github.com/alexanderjoe/LCSymphony/commit/99664a034cef8e8bd3707a1ec9ee09f7866fe570 adds the recommended config options and the default values are set to the current mod selections of online and skip terminal.
